- hosts: localhost
  vars:
    source_key: "./.ssh/id_ed25519"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_ed25519"
    lazygit_version: "0.41.0"
  become: true
  pre_tasks:
    - name: Update Apt
      become: true
      apt:
        force_apt_get: true
        update_cache: true
        state: present
      tags:
        - install
  tasks:
    - include_tasks: tasks/ssh.yml
    - include_tasks: tasks/core.yml
    - include_tasks: tasks/zsh.yml
    - include_tasks: tasks/dotfiles.yml
    - include_tasks: tasks/tools.yml
    - include_tasks: tasks/neovim.yml
    - include_tasks: tasks/node.yml
