- name: Install core packages
  become: yes
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - curl
    - tar
    - cmake
    - gnome-tweaks
    - gnome-shell-extensions
  tags:
    - core
    - install
- name: Enable shell themes
  shell: gnome-extensions enable user-theme@gnome-shell-extensions.gcampax.github.com

- name: Download Cargo Installer
  get_url:
    url: https://sh.rustup.rs
    dest: /tmp/sh.rustup.rs
    mode: "0755"
    force: "yes"
  tags:
    - core
    - install

- name: install rust/cargo
  shell: /tmp/sh.rustup.rs -y
  become: true
  become_user: jimvid
  tags:
    - core
    - install
