- name: Installing stow
  apt: name=stow
  tags:
    - install
    - dotfiles
    - stow
- name: Cloning .dotfiles
  become: true
  become_user: jimvid
  ansible.builtin.git:
    repo: "https://github.com/Jimvid/.dotfiles.git"
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    recursive: yes
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  become: true
  become_user: jimvid
  shell: cd $HOME/.dotfiles && stow . --adopt
  tags:
    - install
    - dotfiles
    - stow
- name: Reset adopted files
  become: true
  become_user: jimvid
  shell: cd $HOME/.dotfiles && git reset --hard
  tags:
    - install
    - dotfiles
    - stow
