- name: Install zsh
  apt: name=zsh
  tags:
    - zsh
    - install
- name: Change default shell
  shell: chsh -s $(which zsh)
  tags:
    - zsh
    - install
- name: Install oh-my-zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" "" --keep-zshrc
  become: true
  become_user: jimvid
  tags:
    - zsh
    - install
- name: Install fzf-tab plugin
  shell: git clone https://github.com/Aloxaf/fzf-tab ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/fzf-tab
  become: true
  become_user: jimvid
  tags:
    - zsh
    - install
- name: Install autosuggestions plugin
  shell: git clone https://github.com/zsh-users/zsh-autosuggestions ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-autosuggestions
  become: true
  become_user: jimvid
  tags:
    - zsh
    - install
- name: Install highlighting plugin
  shell: git clone https://github.com/zsh-users/zsh-syntax-highlighting.git ${ZSH_CUSTOM:-~/.oh-my-zsh/custom}/plugins/zsh-syntax-highlighting
  become: true
  become_user: jimvid
  tags:
    - zsh
    - install
